# Generated by Django 4.2.24 on 2025-11-04 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportStub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('view_reports', 'Xem báo cáo'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
