# Generated by Django 4.2.24 on 2025-10-21 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinfo',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='Chữ ký điện tử'),
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='signature_document',
            field=models.FileField(blank=True, null=True, upload_to='signed_docs/', verbose_name='Văn bản xác nhận đã ký'),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='work_status',
            field=models.CharField(choices=[('nhan_vien_van_phong', 'Nhân viên văn phòng'), ('cong_nhan', 'Công nhân'), ('tu_do', 'Tự do'), ('sinh_vien', 'Sinh viên'), ('khac', 'Khác')], max_length=50, verbose_name='Trạng thái công việc'),
        ),
    ]
